const DS={autoScanEnabled:true,rulesEngineEnabled:true,aiClassificationEnabled:true,parseAttachments:false,aiProvider:'openai',openaiKey:'',claudeKey:'',openaiModel:'gpt-4o-mini',claudeModel:'claude-sonnet-4-20250514',rules:[],parentLabel:'EMAIL_SORTER',confidenceThreshold:0.75,maxEmailsPerScan:50,scanIntervalMinutes:10,whitelist:'',blacklist:''};
let cs={};
document.addEventListener('DOMContentLoaded',()=>{loadSettings();loadStats();checkUpdate();setupEvents();});
function loadSettings(){chrome.runtime.sendMessage({action:'getSettings'},r=>{if(chrome.runtime.lastError)return;cs=r||DS;updateUI();});}
function loadStats(){chrome.runtime.sendMessage({action:'getStats'},s=>{if(chrome.runtime.lastError||!s)return;st('statProcessed',s.processed||0);st('statRules',s.rulesMatched||0);st('statAI',s.aiMatched||0);st('statLabeled',s.labeled||0);});}
function checkUpdate(){chrome.runtime.sendMessage({action:'getUpdateInfo'},i=>{if(chrome.runtime.lastError||!i||!i.hasUpdate)return;const b=document.getElementById('updateBanner'),v=document.getElementById('updateVersionText'),l=document.getElementById('updateLink'),dl=document.getElementById('downloadUpdateBtn');if(b)b.classList.add('show');if(v)v.textContent=' ('+i.currentVersion+' \u2192 '+i.remoteVersion+')';if(l)l.href=i.downloadUrl;if(dl){dl.style.display='inline-block';dl.onclick=e=>{e.preventDefault();dl.textContent='Stahuji...';dl.disabled=true;chrome.runtime.sendMessage({action:'downloadUpdate',url:i.downloadUrl,version:i.remoteVersion},r=>{if(r&&r.success){dl.textContent='Stazeno!';msg('ZIP stazen do Stazenych souboru. Rozbalte a nahradte soubory rozsireni.',false);}else{dl.textContent='Stahnout ZIP';dl.disabled=false;msg(r?.error||'Chyba stahovani',true);}});};}});}
function updateUI(){tog('toggleAutoScan',cs.autoScanEnabled);tog('toggleRulesEngine',cs.rulesEngineEnabled);tog('toggleAI',cs.aiClassificationEnabled);tog('toggleAttachments',cs.parseAttachments);const od=document.getElementById('openaiDot'),cd=document.getElementById('claudeDot');if(od)od.className='api-dot '+((cs.openaiKey||'').length>0?'on':'off');if(cd)cd.className='api-dot '+((cs.claudeKey||'').length>0?'on':'off');}
function setupEvents(){oc('toggleAutoScan',()=>flip('toggleAutoScan','autoScanEnabled'));oc('toggleRulesEngine',()=>flip('toggleRulesEngine','rulesEngineEnabled'));oc('toggleAI',()=>flip('toggleAI','aiClassificationEnabled'));oc('toggleAttachments',()=>flip('toggleAttachments','parseAttachments'));oc('processBtn',doProcess);oc('settingsBtn',doSettings);oc('testOpenAI',()=>doTest('openai'));oc('testClaude',()=>doTest('claude'));oc('checkUpdateBtn',e=>{e.preventDefault();doCheckUpdate();});}
function flip(eid,key){const e=document.getElementById(eid);if(!e)return;const v=!e.classList.contains('active');cs[key]=v;tog(eid,v);chrome.runtime.sendMessage({action:'saveSettings',settings:cs},r=>{if(chrome.runtime.lastError){cs[key]=!v;tog(eid,!v);}});}
function doProcess(){const b=document.getElementById('processBtn');if(b){b.disabled=true;b.textContent='Zpracovavam...';}chrome.runtime.sendMessage({action:'processEmails',settings:cs},r=>{if(b){b.disabled=false;b.textContent='Zpracovat';}if(chrome.runtime.lastError||!r){msg('Chyba',true);return;}if(r.success&&r.data){msg('Zpracovano: '+r.data.processed+', oznaceno: '+r.data.labeled,false);st('statProcessed',r.data.processed||0);st('statRules',r.data.rulesMatched||0);st('statAI',r.data.aiMatched||0);st('statLabeled',r.data.labeled||0);}else if(r.success===false)msg(r.error||'Chyba',true);});}
function doSettings(){chrome.tabs.query({url:'*://mail.google.com/*'},tabs=>{if(tabs&&tabs.length>0){chrome.tabs.sendMessage(tabs[0].id,{action:'openSidebar'},()=>{});chrome.tabs.update(tabs[0].id,{active:true});}else msg('Otevrete Gmail',true);});}
function doTest(p){const bid=p==='openai'?'testOpenAI':'testClaude',rid=p==='openai'?'openaiResult':'claudeResult';const b=document.getElementById(bid),re=document.getElementById(rid);const k=p==='openai'?cs.openaiKey:cs.claudeKey,m=p==='openai'?cs.openaiModel:cs.claudeModel;if(!k||!k.trim()){if(re){re.textContent='API klic neni nastaven';re.className='api-result show error';}return;}if(b){b.disabled=true;b.textContent='Testuji...';b.className='btn-test-api';}chrome.runtime.sendMessage({action:'testAPI',provider:p,apiKey:k,model:m},r=>{if(b){b.disabled=false;}if(r&&r.success){if(b){b.textContent='OK!';b.className='btn-test-api success';}if(re){re.textContent=r.message;re.className='api-result show success';}}else{if(b){b.textContent='Chyba';b.className='btn-test-api error';}if(re){re.textContent=r?r.error:'Chyba';re.className='api-result show error';}}setTimeout(()=>{if(b){b.textContent='Otestovat';b.className='btn-test-api';}},5000);});}
function doCheckUpdate(){const b=document.getElementById('checkUpdateBtn');if(b)b.textContent='Kontroluji...';chrome.runtime.sendMessage({action:'checkForUpdates'},r=>{if(b)b.textContent='Zkontrolovat aktualizace';if(r&&r.hasUpdate){msg('Nova verze '+r.remoteVersion+'!',false);const bn=document.getElementById('updateBanner'),v=document.getElementById('updateVersionText'),l=document.getElementById('updateLink');if(bn)bn.classList.add('show');if(v)v.textContent=' ('+r.currentVersion+' \u2192 '+r.remoteVersion+')';if(l)l.href=r.downloadUrl;}else if(r&&r.success)msg('Nejnovejsi verze!',false);else msg(r?.error||'Chyba',true);});}
function st(id,t){const e=document.getElementById(id);if(e)e.textContent=t;}
function tog(id,a){const e=document.getElementById(id);if(!e)return;if(a)e.classList.add('active');else e.classList.remove('active');}
function oc(id,fn){const e=document.getElementById(id);if(e)e.addEventListener('click',fn);}
function msg(t,err){const e=document.getElementById('statusMessage');if(!e)return;e.textContent=t;e.className='status-message show'+(err?' error':'');setTimeout(()=>e.classList.remove('show'),4000);}
chrome.runtime.onMessage.addListener(r=>{if(r.action==='statusUpdate')loadStats();});
